name: "mlp_model"
platform: "tensorrt_plan"
max_batch_size: 8
input [
  {
    name: "input"
    data_type: TYPE_FP16
    dims: [1408]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP16
    dims: [15]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]