defaults:
  # - override hydra/sweeper/sampler: tpe
  - optimizer: adam
  - scheduler: cyclic
  - loss: FocalLoss
  - dataset: classification
  - model: mlp
  - override hydra/sweeper: optuna
  - _self_

max_epochs: 100
optimized_metric: "val_f1"

hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 20

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      n_startup_trials: 10 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      # scheduler: glob(*,exclude=steplr)
      scheduler.body.max_lr: interval(1e-5, 5e-4)
      scheduler.body.base_lr: interval(1e-6, 5e-6)
      # scheduler.body.warmup_steps: range(100, 1000, 50)
      loss.gamma: interval(0, 3)
