version: '3.5'

services:
  adapter:
    build:
      context: .
      dockerfile: services/adapter/Dockerfile
    volumes:
      - ./storage/:/storage/
      - ./weights/:/weights/
    environment:
      - LOGURU_LEVEL=${LOGURU_LEVEL}
    deploy:
      replicas: ${NUM_REPLICAS}
    network_mode: "host"
  

  bot:
    build:
      context: .
      dockerfile: services/bot/Dockerfile
    volumes:
      - ./storage/:/storage/
    environment:
      - LOGURU_LEVEL=${LOGURU_LEVEL}
    network_mode: "host"

  fastapi:
    build:
      context: .
      dockerfile: services/fastapi/Dockerfile
    volumes:
        - ./storage/:/storage/