version: '3.5'

services:

  adapter:
    build:
      context: .
      dockerfile: services/adapter/Dockerfile
    volumes:
      - ./storage/:/storage/
      - ./weights/:/weights/
    environment:
      - LOGURU_LEVEL=${LOGURU_LEVEL}
    deploy:
      replicas: 1
    network_mode: "host"

  bot:
    build:
      context: .
      dockerfile: services/bot/Dockerfile
    volumes:
      - ./storage/:/storage/
    environment:
      - LOGURU_LEVEL=${LOGURU_LEVEL}
    network_mode: "host"
  
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: services/backend/Dockerfile
      args:
        - DEFAULT_WEBHOOK_URL = "http://php:8120/upload_result.php"
    volumes:
      - ./backend/familiars/:/storage
    ports:
      - 8102:8102

  php:
   container_name: php
   build:
     context: ./services/frontend
     dockerfile: docker/php/Dockerfile
     args:
       - FASTAPI_URL = "http://fastapi:8102"
   volumes:
     - ./services/frontend/src/:/var/www/html/

  php-apache-environment:
   container_name: php-apache
   build:
     context: ./services/frontend
     dockerfile: docker/php-apache/Dockerfile
     args:
       - FASTAPI_URL = "http://fastapi:8102"
   volumes:
     - ./services/frontend/src/:/var/www/html/
     - ./services/frontend/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
   ports:
     - 8020:80

  mysql:
   container_name: mysql
   image: mysql:8
   environment:
     - MYSQL_ROOT_PASSWORD=ROOT

  phpmyadmin:
   container_name: phpmyadmin
   image: phpmyadmin
   restart: always
   ports:
     - 9020:80
   environment:
     - PMA_ARBITRARY=1