collection_name: museum_features
retrieval_threshold: 0.9
storage_folder: storage
bot_topic: bot_output
backend_topic: backend_output

rabbit:
  RABBIT_URL: amqp://guest:guest@localhost:5672/
  INPUT_TOPIC: input
  OUTPUT_TOPICS: [output, backend_output, bot_output]

milvus:
  MILVUS_ALIAS: default
  MILVUS_HOST: localhost
  MILVUS_PORT: 19530
  MILVUS_USER: root 
  MILVUS_PASS: Milvus

triton_ensemble_caption:
  input_names: ['input']
  input_shape: [[-1, 3, 364, 364]]
  input_dtype: ['FP16']
  output_names: ['text_output']
  url: 'localhost:8001'
  model_name: 'ensemble_model_caption'
  model_version: '1'
  connect_type: 'grpc'

triton_ensemble_classify:
  input_names: ['input']
  input_shape: [[-1, 3, 364, 364]]
  input_dtype: ['FP16']
  output_names: ['logits']
  url: 'localhost:8001'
  model_name: 'ensemble_model_classify'
  model_version: '1'
  connect_type: 'grpc'

triton_text_model:
  input_names: ['visual_features']
  input_shape: [[-1, 32, 2048]]
  input_dtype: ['FP16']
  output_names: ['text_output']
  url: 'localhost:8001'
  model_name: 'text_model'
  model_version: '1'
  connect_type: 'grpc'

triton_vision_model:
  input_names: ['input']
  input_shape: [[-1, 3, 364, 364]]
  input_dtype: ['FP16']
  output_names: ['output', 'pooled_output']
  url: 'localhost:8001'
  model_name: 'vision_model'
  model_version: '1'
  connect_type: 'grpc'